spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/fincore_user
    username: postgres
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

logging:
  level:
    org.springframework.security: INFO